Adding GetEvents component
BHoM/Dynamo_Toolkit pull request #274
Opened 2020-11-04 09:28 UTC by adecler

### NOTE: Depends on 
https://github.com/BHoM/BHoM_UI/pull/331
   
### Issues addressed by this PR
See https://github.com/BHoM/BHoM_UI/pull/331

### Additional comments
If you found yourself in the situation where the component fails (silently) to create itself, make sure to manually clean the BHoM folders in `AppData\Roaming\Dynamo` for 2.3 (core and Revit). It seems that the installer is still copying the dlls there therefore creating a conflict with the dll in `ProgramData/BHoM`.

2020-11-05 12:26 UTC, pawelbaran approved these changes
LGTM, the component is exposed correctly

2020-11-05 17:40 UTC, FraserGreenroyd submitted a review, later dismissed
LGTM

2020-11-05 17:40 UTC, FraserGreenroyd commented
/azp run Dynamo_Toolkit.CheckInstaller

2020-11-06 11:38 UTC, pawelbaran requested changes
Taking back my previous review 🙊 Looks like 2.0 + Revit 2018 works perfect, but keeps on crashing badly when trying to place the component on 2.3 + Revit 2020:

![image](https://user-images.githubusercontent.com/26874773/98362068-e7878400-202c-11eb-9a2b-959dec308ba3.png)

2020-11-11 07:34 UTC, adecler commented
@pawelbaran , this didn't crash for me. Did you follow the procedure in the `Additional comments` section before testing ?

That being said, when testing for the crash, I noticed I couldn't create the `GetEvents` from the global search menu. That is fixed with the latest commit.

2020-11-12 11:13 UTC, pawelbaran approved these changes
Seems to be working fine on both 2018 + 2.0 as well as 2020 + 2.3 now 👍 LGTM!

2020-11-12 22:36 UTC, FraserGreenroyd approved these changes
I'm still happy

2020-11-12 22:36 UTC, FraserGreenroyd commented
/azp run Dynamo_Toolkit.CheckInstaller

2020-11-13 03:09 UTC, merged